#+title: Week One
#+author: Karl Statz
#+email: kstatz@colum.edu
* Welcome
Welcome to C++ I. My name is Karl Statz and this is my 8th semester teaching this class! A little about my background: I am a veteran software engineer with 15 years of experience writing code from web video platforms to backend financial systems. My current role is Software Architect at the construction software company RhinoDox where I design and implement Distributed software for construction bid proposals.

While I don't have official office hours, I am usually online in Teams and via Email most ours of the day to answer questions.
* Getting Help
There are wonderful tutors in this department who have taken this class with me. Feel free to book some time with them if you have questions or I am not available to answer a question.
* Homework
There are no tests in this class because I feel like giving tests is the wrong way to asses weather or not you understand the concepts. The only way to learn to code is to write code. So in this class we will be writing a lot of it. I recommend committing _everything_ to github. A) this is a great practice for your eventual career and B) it can save your ass in case of catastrophic computer accidents.
* Course setup
This course starts withe the C Programming language to get our feet wet in a systems language with virtually no creature comforts.
